[#H14] Added files OOP
Chudopal/PythonDeveloperCheatSheet pull request #45
Opened 2022-06-06 19:03 UTC by Starowoitowa

2022-06-07 08:45 UTC, Chudopal commented
Нужно сделать 2 задачки минимум

2022-06-07 09:29 UTC, Starowoitowa commented
Я же потом могу 3 и, если вдруг 4, делать просто отдельными ПР? Для практики я от них не отказываюсь на будущее

2022-06-07 09:40 UTC, Chudopal commented
> Я же потом могу 3 и, если вдруг 4, делать просто отдельными ПР? Для практики я от них не отказываюсь на будущее

Дач конечно

2022-06-07 09:47 UTC, Chudopal requested changes
Вообще, нормально получилось, исправь замечания касательно магии с uuid'ами и будет супер

2022-06-07 09:47 UTC, Chudopal commented on Shops/travel_guide_store/Homeworks/managment.py
> +        self.uuid = uuid
uuid лучше создавать тут через `uuid = uuid4()`

2022-06-07 09:47 UTC, Chudopal commented on Shops/travel_guide_store/Homeworks/managment.py
> +    def __init__ (self, name:str, age: int, role: str, experience: int, sector: str):
ты не передаешь uuid сюда, хотя этого требует родительский класс

2022-06-07 09:47 UTC, Chudopal commented on Shops/travel_guide_store/Homeworks/managment.py
> +        super().__init__(self,name, age)
тут тоже нужно передавать uuid

2022-06-07 10:56 UTC, Starowoitowa commented on Shops/travel_guide_store/Homeworks/managment.py
> +        self.uuid = uuid
Без self?

2022-06-07 13:10 UTC, Chudopal commented on Shops/travel_guide_store/Homeworks/managment.py
> +        self.uuid = uuid
С ним) это я просто пример привел

2022-06-07 13:11 UTC, Chudopal commented on Shops/travel_guide_store/Homeworks/managment.py
> +        self.uuid = uuid
Если ты сделаешь его генерируется тут, то его не придётся везде генерить

2022-06-07 13:11 UTC, Starowoitowa commented on Shops/travel_guide_store/Homeworks/managment.py
> +    def __init__ (self, name:str, age: int, role: str, experience: int, sector: str):
Тогда у меня вопрос: когда мы делали на занятиях примеры с наследованием, мы тоже не передавали uuid из родительского класса (например, там где доктор и пациент наследуют от Человека ни у одного ни у другого uuid не передавался)

2022-06-07 14:21 UTC, Starowoitowa commented on Shops/travel_guide_store/Homeworks/managment.py
> +    def __init__ (self, name:str, age: int, role: str, experience: int, sector: str):
а посмотри теперь?

2022-06-08 15:29 UTC, Chudopal approved these changes
Хорошо, дз принято, можешь мержить. Согласен, что "Починить авто" - это задача для IT-отдела =)

2022-06-08 18:45 UTC, merged