[#H15] Added Animals
Chudopal/PythonDeveloperCheatSheet pull request #52
Opened 2022-06-07 19:04 UTC by Denis9505

Задание про животный мир

2022-06-08 15:15 UTC, Chudopal requested changes
Еще не готово для ready for review, так как присутствует только одна задачка. 
Кроме того, если выставил `help wanted`, добавляй еще кого-то, кроме меня в ревьеры.

2022-06-08 15:15 UTC, Chudopal commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +        self.uuid = uuid
uuid советую генерить прямо здесь типа `self.uuid = uuid4()`, а не передавать его откуда-то

2022-06-08 15:15 UTC, Chudopal commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +    def get_positive_task(self):
в принципе хорошо что отдельными методами это сделал. Теперь просто сделай еще один метод, который будет вызывать эти методы в зависимости от выполнимости тасочки.

2022-06-08 15:15 UTC, Chudopal commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +        self.task_description = task_description
таска разве является частью сотрудника??? В конструкторе ее точно упомянать не стоит. А тем более то, как ты сделал: ты упомянул только task_description, а это только часть сущности Task.

2022-06-08 16:02 UTC, Denis9505 commented
Окей понял))

2022-06-08 17:44 UTC, Denis9505 commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +        self.uuid = uuid
да я сначала думал об этом((

2022-06-08 17:45 UTC, Denis9505 commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +    def get_positive_task(self):
вот тут я запутался как мне сделать, не могу сообразить что мне надо в if прокинуть что бы задача правильно исполнялась

2022-06-08 17:46 UTC, Denis9505 commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +        self.task_description = task_description
понял

2022-06-08 18:43 UTC, Starowoitowa commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +    def get_positive_task(self):
в if тебе надо прописать, что если опыт сотрудника больше либо равен уровню задачи И  сфера задачи равна сфере сотрудника (либо наоборот сфера сотрудника = сфере задачи), то вызывается позитив таск, иначе - негатив

2022-06-08 19:06 UTC, Denis9505 commented
Ну я подсчитал что выделять кого то, все же не стоит. Кто захочет тот поможет

2022-06-08 19:08 UTC, Chudopal commented
Ну все же не стоит сразу всех беспокоить) сообщение же на почту приходит

2022-06-09 10:04 UTC, Denis9505 commented
Окей, буду дома оставлю 5 человек))

2022-06-09 10:18 UTC, Denis9505 commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +    def get_positive_task(self):
Спасибо за помощь))

2022-06-09 18:57 UTC, Chudopal approved these changes
В принципе твой взгляд на вещи имеет место быть. Можно передавать сотруднику таску, а можно сотрудника таске, как у тебя. Последний подход имеет свои ограничения, например не может существовать таски без сотрудника, который ее должен выполнять, хотя для многих компаний это является нормой.
Но взгляд на вещи интересный. Дз принята, можешь мержить после фикса uuid, что я описал в комментах

2022-06-09 18:57 UTC, Chudopal commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +    def __init__(self, name: str, uuid: UUID, age: int) -> None:
зачем ты передаешь uuid, если дальше он нигде не используется? У тебя в конструкторе происходит автогенерация uuid, его не нужно передавать извне

2022-06-09 19:22 UTC, Denis9505 commented on Shops/sport_atribute_shop/home_work/[#H15]Manegment.py
> +    def __init__(self, name: str, uuid: UUID, age: int) -> None:
Понял, уберу этот аргумент)

2022-06-10 15:56 UTC, merged