[#D04] (add SQL)
Chudopal/PythonDeveloperCheatSheet pull request #66
Opened 2022-06-20 07:07 UTC by jiaxer

2022-06-20 21:22 UTC, Chudopal requested changes
Все ОК, просто подправь пару мест

2022-06-20 21:22 UTC, Chudopal commented on Shops/rubiks_cube_shop/app/main.py
> +        """.format(name, price))
Мне кажется или не хватает self._cursor.commit()?

2022-06-20 21:22 UTC, Chudopal commented on Shops/rubiks_cube_shop/app/main.py
> +        """.format(name))
То же самое, не сохраняешь изменения в БД. self._cursor.commit()

2022-06-20 21:22 UTC, Chudopal commented on Shops/rubiks_cube_shop/app/main.py
> +            result[i[0]] = i[1]
можно чуть более информативно чем просто i?

2022-06-21 07:00 UTC, jiaxer commented on Shops/rubiks_cube_shop/app/main.py
> +        """.format(name, price))
Забыл, когда проверял оно сохранялось и по этому не обратил внимание, что после перезапуска все новое сбрасывалось. Только не  self._cursor.commit(), а self._connection.commit()

2022-06-21 08:13 UTC, Chudopal commented on Shops/rubiks_cube_shop/app/main.py
> +        """.format(name, price))
Да, connection

2022-06-21 08:15 UTC, Chudopal approved these changes
 Все ОК, можно мержить

2022-06-21 08:46 UTC, merged